/*
 * Copyright 2013, Gerasim Troeglazov, 3dEyes@gmail.com. All rights reserved.
 * Distributed under the terms of the MIT License.
 */

#include "TesseractLanguages.h"

lang_info gLngInfo[] = {
				   {"eng",		"English"},
				   {"rus",		"Russian"},
				   {"grc",		"Ancient Greek"},
				   {"epo",		"Esperanto"},
				   {"epo_alt",	"Esperanto alternative"},
				   {"ukr",		"Ukrainian"},
				   {"tur",		"Turkish"},
				   {"tha",		"Thai"},
				   {"tgl",		"Tagalog"},
				   {"tel",		"Telugu"},
				   {"tam",		"Tamil"},
				   {"swe",		"Swedish"},
				   {"swa",		"Swahili"},
				   {"srp",		"Serbian (Latin)"},
				   {"sqi",		"Albanian"},
				   {"spa",		"Spanish"},
				   {"spa_old",	"Spanish (Old)"},
				   {"slv",		"Slovenian"},
				   {"slk",		"Slovakian"},
				   {"slk-frak",	"Slovakian (Fraktur)"},
				   {"ron",		"Romanian"},
				   {"por",		"Portuguese"},
				   {"pol",		"Polish"},
				   {"nor",		"Norwegian"},
				   {"nld",		"Dutch"},
				   {"msa",		"Malay"},
				   {"mlt",		"Maltese"},
				   {"mkd",		"Macedonian"},
				   {"mal",		"Malayalam"},
				   {"lit",		"Lithuanian"},
				   {"lav",		"Latvian"},
				   {"kor",		"Korean"},
				   {"kan",		"Kannada"},
				   {"ita",		"Italian"},
				   {"ita_old",	"Italian (Old)"},
				   {"isl",		"Icelandic"},
				   {"ind",		"Indonesian"},
				   {"chr",		"Cherokee"},
				   {"hun",		"Hungarian"},
				   {"hrv",		"Croatian"},
				   {"hin",		"Hindi"},
				   {"heb",		"Hebrew"},
				   {"glg",		"Galician"},
				   {"frm",		"Middle French"},
				   {"frk",		"Frankish"},
				   {"fra",		"French"},
				   {"fin",		"Finnish"},
				   {"eus",		"Basque"},
				   {"est",		"Estonian"},
				   {"equ",		"Math"},
				   {"enm",		"Middle English"},
				   {"ell",		"Greek"},
				   {"deu",		"German"},
				   {"dan",		"Danish"},
				   {"dan-frak",	"Danish (Fraktur)"},
				   {"ces",		"Czech"},
				   {"cat",		"Catalan"},
				   {"bul",		"Bulgarian"},
				   {"ben",		"Bengali"},
				   {"bel",		"Belarusian"},
				   {"aze",		"Azerbaijani"},
				   {"ara",		"Arabic"},
				   {"afr",		"Afrikaans"},
				   {"jpn",		"Japanese"},
				   {"chi_sim",	"Chinese (Simplified)"},
				   {"chi_tra",	"Chinese (Traditional)"},
				   {"vie",		"Vietnamese"},
				   {"deu-frak",	"German (Fraktur)"},
				   {"swe-frak",	"Swedish (Fraktur)"},
				   {"",			""}
};
